version: '3.9'

services:
  phpunit:
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: postgres:14.2-alpine
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
