version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/${DOCKER_APP_RUNTIME:-php7.3}/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_DATABASE}"]
      interval: 3s
      timeout: 5s
