version: '3.9'

services:
  phpunit:
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    tmpfs: /var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    healthcheck:
      test: mysql --user=$${MYSQL_USER} --password=$${MYSQL_PASSWORD} --silent --execute 'SHOW DATABASES;'
      interval: 10s
      timeout: 5s
      retries: 5
