version: '3.9'

services:
  composer:
    build:
      dockerfile: .docker/php${PHP_VERSION:-7.3}/Dockerfile
    environment:
      COMPOSER_CACHE_DIR: /app/.cache/composer
    volumes:
      - ./:/app
    entrypoint: composer

  phpunit:
    build:
      dockerfile: .docker/php${PHP_VERSION:-7.3}/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      database:
        condition: service_healthy
    entrypoint: vendor/bin/phpunit

  database:
    build:
      dockerfile: .docker/${DB_CONNECTION:-pgsql}/Dockerfile

  php-cs-fixer:
    build:
      dockerfile: .docker/php${PHP_VERSION:-7.3}/Dockerfile
    volumes:
      - ./:/app
    entrypoint: vendor/bin/php-cs-fixer
