name: PHPUnit

on: [ push, pull_request ]

jobs:
  test:
    name: Run PHPUnit [PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, ${{ matrix.dependencies }}]

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.3', '7.4', '8.0', '8.1', '8.2' ]
        laravel: [ '8.*', '9.*' ]
        dependencies: [ lowest, highest ]
        exclude:
          - laravel: '9.*'
            php: '7.3'
          - laravel: '9.*'
            php: '7.4'

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build containers
        run: docker compose build

      - name: Install Laravel using Composer
        run: docker compose run composer require laravel/framework:${{ matrix.laravel }} --no-interaction --no-progress --no-update

      - name: Install Composer dependencies
        if: ${{ matrix.dependencies }} == highest
        run: docker compose run composer update --no-interaction --no-progress

      - name: Install lowest Composer dependencies
        if: ${{ matrix.dependencies }} == lowest
        run: docker compose run composer update --prefer-lowest --prefer-stable --no-interaction --no-progress

      - name: Run PHPUnit
        run: docker compose run phpunit

  coverage:
    name: Analyze code coverage

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: 7.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build containers
        run: docker compose build

      - name: Install Composer dependencies
        run: docker compose run composer install --no-interaction --no-progress

      - name: Run PHPUnit with a coverage analysis
        run: docker compose run phpunit --coverage-clover coverage.xml

      - name: Upload the coverage report
        uses: codecov/codecov-action@v3
